
const customerData = [
    {
        id: 1,
        profileUrl:"https://github.com/shadcn.png",
        name: "John Doe",
        email: "john.doe@example.com",
        package: "Standard",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",

    },
    {
        id: 2,
        profileUrl:"https://github.com/shadcn.png",
        name: "Jane Smith",
        email: "jane.smith@example.com",
        package: "Deluxe",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",

    },
    {
        id: 3,
        profileUrl:"https://github.com/shadcn.png",
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        package: "Suite",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 4,
        profileUrl:"https://github.com/shadcn.png",
        name: "Bob Brown",
        email: "bob.brown@example.com",
        package: "Standard",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 5,
        profileUrl:"https://github.com/shadcn.png",
        name: "Cathy White",
        email: "cathy.white@example.com",
        package: "Premium",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 6,
        profileUrl:"https://github.com/shadcn.png",
        name: "David Green",
        email: "david.green@example.com",
        package: "Basic",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 7,
        profileUrl:"https://github.com/shadcn.png",
        name: "Emily Blue",
        email: "emily.blue@example.com",
        package: "Deluxe",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 8,
        profileUrl:"https://github.com/shadcn.png",
        name: "Frank Black",
        email: "frank.black@example.com",
        package: "Standard",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 9,
        profileUrl:"https://github.com/shadcn.png",
        name: "Grace Red",
        email: "grace.red@example.com",
        package: "Premium",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
    {
        id: 10,
        profileUrl:"https://github.com/shadcn.png",
        name: "Harry Gold",
        email: "harry.gold@example.com",
        package: "Basic",
        booking: "Confirmed",
        roomType: "Single",
        arrive: "2024-07-25",
        payment: "Paid",
    },
];

export default customerData;
